 export const getLimitsJSON = [
    {
        "response": {
            "single": {
                "minStakeSingleBet": "100.00",
                "maxStakeSingleBet": "50000.00",
                "maxWinSingleBet": "5000000.00"
            },
            "system": {
                "minStakeSystemBet": "100.00",
                "maxWinSystemBet": "5000000.00",
                "maxStakeSystemBet": "50000.00",
                "maxOdd": "50000.00",
                "maxSystemBet": "10"
            },
            "allways": "true",
            "multiple": {
                "minStakeCombiBet": "100.00",
                "minCombination": "2",
                "maxCombination": "10",
                "combiLimits": [{
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "14"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "10"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "13"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "7"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "3"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "18"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "4"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "9"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "15"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "12"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "20"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "2"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "17"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "8"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "5"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "16"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "19"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "11"
                }, {
                    "manipulationFee": "0.00",
                    "manipulationFee_Livebet": "0.00",
                    "limit": "5000000.00",
                    "tipSize": "6"
                }],
                "maxStakeCombi": "50000.00"
            },
            "bonusfromodd": "1.30",
            "bonuses": [{
                "bonus": "5.00",
                "tipSize": "20"
            }, {
                "bonus": "5.00",
                "tipSize": "19"
            }, {
                "bonus": "5.00",
                "tipSize": "18"
            }, {
                "bonus": "5.00",
                "tipSize": "17"
            }, {
                "bonus": "5.00",
                "tipSize": "16"
            }, {
                "bonus": "5.00",
                "tipSize": "15"
            }, {
                "bonus": "5.00",
                "tipSize": "14"
            }, {
                "bonus": "5.00",
                "tipSize": "13"
            }, {
                "bonus": "5.00",
                "tipSize": "12"
            }, {
                "bonus": "5.00",
                "tipSize": "11"
            }, {
                "bonus": "5.00",
                "tipSize": "10"
            }, {
                "bonus": "2.00",
                "tipSize": "9"
            }, {
                "bonus": "2.00",
                "tipSize": "8"
            }, {
                "bonus": "2.00",
                "tipSize": "6"
            }, {
                "bonus": "2.00",
                "tipSize": "5"
            }, {
                "bonus": "2.00",
                "tipSize": "4"
            }, {
                "bonus": "2.00",
                "tipSize": "3"
            }, {
                "bonus": "2.00",
                "tipSize": "2"
            }]
        },
        "status": "Success"
    }
]